-- MySQL Script generated by MySQL Workbench
-- 02/18/19 09:24:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsiscoop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsiscoop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsiscoop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbsiscoop` ;

-- -----------------------------------------------------
-- Table `dbsiscoop`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`planc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`planc` (
  `idplanc` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idplanc`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_planc_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_planc_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbsiscoop`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`socio` (
  `idsocio` INT NOT NULL AUTO_INCREMENT,
  `nsocio` INT NOT NULL,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `fecha_nac` VARCHAR(20) NULL,
  `fecha_ins` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `condicion` VARCHAR(8) NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`idsocio`),
  UNIQUE INDEX `nsocio_UNIQUE` (`nsocio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `cargo` VARCHAR(20) NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `imagen` VARCHAR(50) NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`contrato` (
  `idcontrato` INT NOT NULL AUTO_INCREMENT,
  `idsocio` INT NOT NULL,
  `ncontrato` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `condicion` VARCHAR(15) NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`idcontrato`),
  INDEX `fk_contrato_socio_idx` (`idsocio` ASC),
  CONSTRAINT `fk_contrato_socio`
    FOREIGN KEY (`idsocio`)
    REFERENCES `dbsiscoop`.`socio` (`idsocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idsocio` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL,
  `num_comprobante` VARCHAR(10) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `total_ingreso` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_ingreso_socio_idx` (`idsocio` ASC),
  INDEX `fk_ingreso_usuario_idx` (`idusuario` ASC),
  INDEX `fk_ingreso_contrato_idx` (`idcontrato` ASC),
  CONSTRAINT `fk_ingreso_socio`
    FOREIGN KEY (`idsocio`)
    REFERENCES `dbsiscoop`.`socio` (`idsocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbsiscoop`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_contrato`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `dbsiscoop`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`detalle_ingreso` (
  `iddetalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `idingreso` INT NOT NULL,
  `idplanc` INT NOT NULL,
  `semana` INT NOT NULL,
  `cantidad_ingreso` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`iddetalle_ingreso`),
  INDEX `fk_detalle_ingreso_ingreso_idx` (`idingreso` ASC),
  INDEX `fk_detalle_ingreso_planc_idx` (`idplanc` ASC),
  CONSTRAINT `fk_detalle_ingreso_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `dbsiscoop`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ingreso_planc`
    FOREIGN KEY (`idplanc`)
    REFERENCES `dbsiscoop`.`planc` (`idplanc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`egreso` (
  `idegreso` INT NOT NULL AUTO_INCREMENT,
  `idsocio` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL,
  `num_comprobante` VARCHAR(10) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `total_egreso` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idegreso`),
  INDEX `fk_egreso_socio_idx` (`idsocio` ASC),
  INDEX `fk_egreso_usuario_idx` (`idusuario` ASC),
  INDEX `fk_egreso_contrato_idx` (`idcontrato` ASC),
  CONSTRAINT `fk_egreso_socio`
    FOREIGN KEY (`idsocio`)
    REFERENCES `dbsiscoop`.`socio` (`idsocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_egreso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbsiscoop`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_egreso_contrato`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `dbsiscoop`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`detalle_egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`detalle_egreso` (
  `iddetalle_egreso` INT NOT NULL AUTO_INCREMENT,
  `idegreso` INT NOT NULL,
  `idplanc` INT NOT NULL,
  `semana` INT NOT NULL,
  `cantidad_egreso` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`iddetalle_egreso`),
  INDEX `fk_detalle_egreso_egreso_idx` (`idegreso` ASC),
  INDEX `fk_detalle_egreso_planc_idx` (`idplanc` ASC),
  CONSTRAINT `fk_detalle_egreso_egreso`
    FOREIGN KEY (`idegreso`)
    REFERENCES `dbsiscoop`.`egreso` (`idegreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_egreso_planc`
    FOREIGN KEY (`idplanc`)
    REFERENCES `dbsiscoop`.`planc` (`idplanc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`usuario_permiso` (
  `idusuario_permiso` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idusuario_permiso`),
  INDEX `fk_usuario_permiso_usuario_idx` (`idusuario` ASC),
  INDEX `fk_usuario_permiso_permiso_idx` (`idpermiso` ASC),
  CONSTRAINT `fk_usuario_permiso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbsiscoop`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_permiso_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `dbsiscoop`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`afiliado` (
  `idafiliado` INT NOT NULL AUTO_INCREMENT,
  `idcontrato` INT NOT NULL,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `condicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idafiliado`),
  INDEX `fk_afiliado_contrato_idx` (`idcontrato` ASC),
  CONSTRAINT `fk_afiliado_contrato`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `dbsiscoop`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`config_inicial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`config_inicial` (
  `idconfig_inicial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `periodo` INT NOT NULL,
  PRIMARY KEY (`idconfig_inicial`),
  UNIQUE INDEX `periodo_UNIQUE` (`periodo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsiscoop`.`config_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsiscoop`.`config_sistema` (
  `idconfig_sistema` INT NOT NULL AUTO_INCREMENT,
  `idconfig_inicial` INT NOT NULL,
  `semanas` INT NOT NULL,
  `costo` DECIMAL(11,2) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  PRIMARY KEY (`idconfig_sistema`),
  INDEX `fk_config_sistema_config_inicial_idx` (`idconfig_inicial` ASC),
  CONSTRAINT `fk_config_sistema_config_inicial`
    FOREIGN KEY (`idconfig_inicial`)
    REFERENCES `dbsiscoop`.`config_inicial` (`idconfig_inicial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
